### ISSUE TITLE
Interest

### ISSUE THREAD

**Issue by penelopepg** [brainhack-school2020/MarkNelson86_EEGRecogBIDS#1]
Hi Mark,

Your project seems promising! How did you come across such a large data set? Will you be performing time-frequency analysis and look into brain oscillations? 

Best regards,
Pénélope

**Comment by MarkNelson86** [comment]
Hi Penelope, 

  Thanks for your interest. The dataset is actually from my master thesis. I always meant to make it shareable, and now I finally have the time. I think spectral analysis is a good idea. I'm looking primarily at the ERPs of memory encoding, and there's definitely potential for individual differences in the power spectra or oscillatory brain activity. TBH I probably need to read up on it before I begin, so I know what I'm looking for.

  I appreciate your comments. Please share if you have more.
